version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: ../
    dockerfile: docker/Dockerfile.airflow
  
  # FORCE THE DNS BRIDGE TO YOUR MAC HOST:
  extra_hosts:
    - "host.docker.internal:host-gateway"
    
  environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Chicago
      - AIRFLOW__WEBSERVER__SECRET_KEY=this_is_a_very_secure_random_key_12345
      - AIRFLOW__CORE__BASE_LOG_FOLDER=/opt/airflow/logs
      - AIRFLOW__CORE__REMOTE_LOGGING=False
  volumes:
    # Mount your Mac's folders directly into the Airflow container
    - ../orchestration/dags:/opt/airflow/dags
    - ../orchestration/plugins:/opt/airflow/plugins
    - ../src:/opt/airflow/src
    - ../data:/opt/airflow/data
    - ../transform:/opt/airflow/transform
    - ../gx:/opt/airflow/gx
    - ../gold_analytics:/opt/airflow/gold_analytics
  depends_on:
    postgres:
      condition: service_healthy

services:
  # 1. The Memory Brain (Database)
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    ports:
      - "5433:5433"

  # 2. The One-Time Setup Script
  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin

  # 3. The Visual Dashboard
  # 3. The Visual Dashboard
  airflow-webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  # 4. The Background Manager
  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
networks:
  default:
    name: finstream-net
    external: true
